### PR TITLE
[TDF] Add root/dataframe/test_reports.cxx

### PR DESCRIPTION
**Pull request by bluehood**
Simple test for the cutflow report feature

### CODE REVIEW

**Comment by bluehood** [comment]
This patch will have a trivial conflict with #16 or viceversa, according to which one is accepted first, because both tests are added at the end of the `CMakeLists.txt` file. I will fix it when the time comes.

**Comment by dpiparo** [comment]
Hi,
thanks for committing to adapt the PR. I would do it myself but at the moment I think I cannot find the PR enabling the cut flow reports.

**Comment by bluehood** [comment]
Hi,
the patch with the cutflow reports is not there yet because it depends on [this](https://github.com/root-mirror/root/pull/333) other one

**Comment by dpiparo** [comment]
https://github.com/root-mirror/root/pull/333 has been merged and closed just now.

**Comment by bluehood** [comment]
thanks, there is the cutflow reports pr :)

**Comment by dpiparo** [comment]
Merged, thanks.

**Pull request closed without merging**
